services:
  alt_game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alt_game
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - alt_game_network
    volumes:
      - ./src:/app

  redis:
    image: redis:alpine
    container_name: alt_game_redis
    ports:
      - "6380:6379"
    networks:
      - alt_game_network

networks:
  alt_game_network:
    driver: bridge
